--- #YAML:1.0
name:               Mojolicious-Plugin-PgAsync
version:            0.02
abstract:           ~
author:
    - Alexander Romanenko <romanenko@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::Pg:      2.19.0
    Mojolicious:  4.30
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
